### ISSUE TITLE
Help developers by making an Appwrite Tutorial 🎥

### ISSUE THREAD

**Issue by Meldiron** [appwrite/awesome-appwrite#88]
# Introduction

Appwrite has been and always will be a tool for developers. To emphasize this, we want to create the **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to create a tutorial regarding Appwrite. **It can be anything!** How to set up Appwrite, how to use Appwrite service, a demo of some features, presentation about Appwrite permissions... You are limited only by your imagination. **It can be in any form!** You could record a video on Youtube, stream on Twitch, write an article or host an event on the Discord server. As long as there is a record, we will accept your submission.

### Requirements:

- Your tutorial has to be publicly available
- Your tutorial must link to `appwrite` in some way (link, logo in overlay, description...)
- Your video must be at least 5 minutes long (shorter allowed if the quality is top-tier, for example, animation with voice-over)

### Task summary:

- [ ]  Make a tutorial (video, stream, article, presentation...)
- [ ]  Mention Appwrite in some form (link Twitter, website, logo in the video...)
- [ ]  Submit PR to [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite) with a link to your resource

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? Go ahead! We are accepting as many tutorials as the community can create. One note, **quality over quantity.**

**Happy Appwriting!**

**Comment by Vidushi-Gupta** [comment]
Hi, could you assign this to me? Thanks!

**Comment by Mnayu** [comment]
Hey! I'd love to make a tutorial on Appwrite!
Can you assign this to me?

**Comment by Meldiron** [comment]
@Mnayu We don't assign this issue. Go ahead, work on your blog post 😊 This issue is opened for everyone and we want as many quality PRs as our community can create.

**Comment by Mnayu** [comment]
@Meldiron oh okay thanks!
