### ISSUE TITLE
Help developers by building a demo app with Appwrite 🧱

### ISSUE THREAD

**Issue by Meldiron** [appwrite/awesome-appwrite#90]
# Introduction

Appwrite has been and always will be a tool for developers. To emphasize this, we want to create the **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to build a demo application that will use Appwrite under the hood. **It can be anything!** Web app, mobile app, Flutter, Unity, CLI tool... You are limited only by your imagination!

### Requirements:

- Your repository has to be publicly available
- Your repository must use `appwrite` topic
- Your app must be built with Appwrite
- Your app needs to include [Built with Appwrite badge](https://appwrite.io/assets)

### Task summary:

- [ ]  Build a demo app using Appwrite
- [ ]  Prepare nice-looking and informative `README.md` (screenshots more than welcome 🤩)
- [ ]  Submit PR to [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite) with a link to your repo

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? Go ahead! We are accepting as many demo apps as the community can create. One note, **quality over quantity.**

**Happy Appwriting!**

**Comment by Jaideep07** [comment]
Hello 😃, I have never tried appwrite before so this could be my best chance to explore it, I will be glad to work on this!

**Comment by kambleaa007** [comment]
lets try building with AppWrite

**Comment by rdmchr** [comment]
Would something like an Appwrite starter for VueJS be nice to have? It could include stuff like Tailwind so you can get started developing more quickly.

**Comment by christyjacob4** [comment]
@rdmchr  If you're trying to create a starter for Appwrite + VueJS + Tailwind, it would be best if you can create an npx binary that can be directly executed from the command line. 

Something like `npm init appwrite myProject `

**Comment by rdmchr** [comment]
I've never created something like that, but I want to give it a try. I'll be going on a trip soon, but after that, I'll take a look at it. The first version should probably be ready this month if nothing else comes up or I don't heavily underestimate the project.
I don't want to clutter this issue with my or maybe even other peoples ideas, so I [set up a repo](https://github.com/rdmchr/Appwrite-Starter) which allows everyone to request features and outlines my idea. I hope that's okay.

**Comment by divshacker** [comment]
May I work on this please as I am familiar with this issue too

**Comment by rishi-wqd190004** [comment]
Lets try building one with Appwrite :)

**Comment by alceil** [comment]
Is there any framework that does not have a demo app on it? If yes I would like to work on it. It will fun learning that framework and making a demo app for appwrite too

**Comment by lohanidamodar** [comment]
@alceil You can find the list of demos we already officially have [here](https://github.com/appwrite/?q=demo). You will surely find something that we haven't worked with for demo yet.

**Comment by alceil** [comment]
Cool, lemme check it then.

**Comment by alceil** [comment]
Can i make one for ember.js will it be a good idea? @lohanidamodar

**Comment by lohanidamodar** [comment]
> Can i make one for ember.js will it be a good idea? @lohanidamodar

Sure why not. All thebest @alceil

**Comment by alceil** [comment]
Thanks
